version: "3"
services: 
    mongodb:
        container_name: mongodb
        image: "mongo"  
    app:
        container_name: bhub
        build: .
        depends_on: 
            - mongodb
        ports:
            - "5000:5000"
        environment:
            MONGO_DB_HOST: mongodb